site_name: Smash Remix
site_url: https://joaorb64.github.io/smashremix-website/

theme:
  custom_dir: overrides
  name: material
  palette:
    scheme: slate
    primary: red
    accent: red
  logo: "assets/smashremixlogo_icon.webp"
  favicon: assets/smashremixlogo_icon.webp
  features:
    - search.suggest
    # - navigation.sections
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top

plugins:
  - search
  - git-committers:
      enabled: false
      repository: joaorb64/smashremix-website
      branch: main
  - macros

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - styles/modal.css
  - styles/extra.css
  - styles/topbar.css
  - styles/sidebar.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js

nav:
  - Home:
      - index.md
  - Patcher:
      - patcher/index.md
  - Emulator:
      - emulator/index.md
